name: Python Selenium CI

on: push
  #schedule:
  #  - cron: '00 23 * * *'  # Runs at 11 PM UTC, around 9-10 AM AEST depending upon DST

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # This will use the latest version of Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Firefox
      uses: browser-actions/setup-firefox@latest

    - name: Run main script
      run: python bg_run_project.py
      env:
        FMS_SERVER: ${{ secrets.FMS_SERVER }}
        FMS_DATABASE: ${{ secrets.FMS_DATABASE }}
        FMS_USERNAME: ${{ secrets.FMS_USERNAME }}
        FMS_PASSWORD: ${{ secrets.FMS_PASSWORD }}
        SCT_SERVER: ${{ secrets.SCT_SERVER }}
        SCT_DATABASE: ${{ secrets.SCT_DATABASE }}
        SCT_USERNAME: ${{ secrets.SCT_USERNAME }}
        SCT_PASSWORD: ${{ secrets.SCT_PASSWORD }}
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        FTP_REMOTE_PATH: ${{ secrets.FTP_REMOTE_PATH }}
        BEX_HISTORY_URL: ${{ secrets.BEX_HISTORY_URL }}
        BEX_LOGIN_URL: ${{ secrets.BEX_LOGIN_URL }}
        BEX_PASSWORD: ${{ secrets.BEX_PASSWORD }}
        BEX_SEARCH_URL: ${{ secrets.BEX_SEARCH_URL }}
        BEX_USERNAME: ${{ secrets.BEX_USERNAME }}
        SADLEIRS_LOGIN_URL: ${{ secrets.SADLEIRS_LOGIN_URL }}
        SADLEIRS_PASSWORD: ${{ secrets.SADLEIRS_PASSWORD }}
        SADLEIRS_USERNAME: ${{ secrets.SADLEIRS_USERNAME }}
        TFM_LOGIN_URL: ${{ secrets.TFM_LOGIN_URL }}
        TFM_PASSWORD: ${{ secrets.TFM_PASSWORD }}
        TFM_USERNAME: ${{ secrets.TFM_USERNAME }}


       
